"""Swarm-selected layout experiments with an optional verified AOT primitive."""
import hashlib
import json
from pathlib import Path
import subprocess

from examples.optimize_cpu_kernel import host_observation, check_power, power_source
from sera.cpu_kernel_validation import validate_cpu_kernel
from sera.kernel_advisory import KernelAdvisoryTeam
from sera.kernel_search import KernelCandidate, optimize_kernel
from sera.kernel_tools import HillsKernelEvaluator
from sera.storage import save_json

folder = Path(__file__).resolve().parent
repo = folder.parent.parent
prepared = repo/'evidence/cpu-libxsmm-generator-2026-09-25'
reference = repo/'evidence/cpu-libxsmm-reference-2026-09-24'
baseline = prepared/'baseline/kernel.c'
source = baseline.read_text()
source_hash = hashlib.sha256(source.encode()).hexdigest()
correctness = json.loads((prepared/'baseline-correctness-final.json').read_text())
if correctness['source_hash'] != source_hash or not correctness['passed']:
    raise ValueError('Prepared baseline does not match its correctness record')
initial = host_observation()
check_power(initial, initial)
prior = []
for name in ('cpu-libxsmm-measure-prepared-2026-09-24', 'cpu-libxsmm-next-continue-2026-09-25'):
    state = json.loads((repo/'evidence'/name/'agent/state.json').read_text())
    records = []
    for batch in state['rounds']:
        for attempt in batch['implementations']:
            record = {key: attempt[key] for key in
                      ('experiment_id','status','name','hypothesis','reason','source_hash') if key in attempt}
            if 'error' in attempt:
                record['error_type'] = attempt['error'].split(':',1)[0]
            if 'measured_outcome' in attempt:
                record['measured_outcome'] = {key: attempt['measured_outcome'].get(key) for key in
                                              ('scores','control_scores','promoted','adjudication')}
            records.append(record)
    prior.append(dict(phase=name, calls=state['calls'], attempts=state['implementations'], records=records))
reviews = {name:(prepared/name).read_text() for name in
           ('generator-review-luna.md','layout-review-luna.md','measurement-review-luna.md')}
task = '''Optimize the supplied standalone LIBXSMM SME CPU kernel for row-major FP32 C=A@B.
Target strictly >1800 GFLOP/s under the unchanged kernel-opt hill. ABI:
void gemm(int n,const float*A,const float*B,float*C). Main timing n512; preserve
correct general sizes/tails and n<=0. Fixed Apple clang21 flags:
-O3 -march=native -ffast-math -shared -fPIC -lm. Tolerance .002. Single thread,
no external runtime libraries, mixed precision, result/input caching, or scorer edits.
All calls, packing, allocations, SME state transitions, and stores remain timed.
Preserve the complete LIBXSMM BSD license notice. Inputs are fresh on every call.

Current baseline still invokes the original full512 LIBXSMM kernel once. Its source
now includes an OPTIONAL UNUSED offline-generated helper, sera_libxsmm_panel32,
whose exported shape is colmajor M512,N32,K512,lda/ldb/ldc512,beta0,no transpose.
The helper's body is1536 exact generated bytes; it has passed12 deterministic public
panel ABI correctness tests and an internal-branch/no-relocation/no-external-call audit.
The whole augmented baseline passed48 correctness cases. It is a new build identity,
so Sera measures a fresh baseline. No helper performance is yet known.

The helper is declared before gemm and defined as embedded assembly afterward.
It takes const void* parameters[22], with [4]=column-major A pointer,[10]=B,[16]=C;
all remaining fields zero. For row-major 32-row output band starting at r:
parameters[4]=B; parameters[10]=A+r*512; parameters[16]=C+r*512.
Sixteen disjoint bands r=0,32,...,480 cover the full product. This is a legal optional
layout experiment, not a mandatory choice or a measured win. Each call internally
packs the corresponding A row panel into64KiB and enters/exits SME. The original
full512 path packs64 rows into128KiB and does one overall SME entry. Compare the
cache/packing tradeoff against the extra call/state-transition overhead; do not infer
speedup from buffer size alone. Using the helper can be expressed as a small guarded
wrapper edit, without rewriting the long generated assembly. Astra must implement
any selected wrapper and the evaluator will test the full GEMM, not merely a panel.

The 15 Luna specialists jointly propose and rank the next experiments. Astra selects
roles, implements the selected queue, and reviews the measured results. Concrete
layout/packing hypotheses are welcome; do not repeat previously measured instruction
scheduling sources. Roles can propose different legal ways to use the source and
helper, but duplicate descriptions are not distinct experiments. Name exact source
blocks and coordinate all pointer, stride, layout, and traversal changes needed.
Do not constrain a larger layout change to preserve incompatible old strides.
The helper and baseline are imported reference code, not a Sera-discovered improvement.
Only a changed source that passes fresh paired gates can demonstrate an improvement.

Prior phases below are historical context only; never use them as fresh controls.
Retain all AC/battery data separately. This block requires its initial power mode and
settings throughout. The per-agent timeout remains180 seconds, with108 calls,
six total implementation attempts, and1800 seconds overall for this new block.
Historical experiments:\n''' + json.dumps(prior) + '\nSource reviews:\n' + json.dumps(reviews)
profile = dict(cpu='Apple M4 Pro',power=power_source(initial),streaming_fp32_lanes=16,
    capabilities=['cpu','arm64','sme','sme2','neon','simd','single-thread'],
    sme2=True,p_core_l1d_bytes=131072,e_core_l1d_bytes=65536,cache_line_bytes=128)
team = KernelAdvisoryTeam(work_dir=folder/'agent', task=task, profile=profile,
                         max_rounds=6, batch_size=3, max_calls=108, timeout=180)
modules = ('kernel_search.py','kernel_advisory.py','kernel_tools.py','kernel_edits.py',
           'kernel_swarm_plan.py','kernel_advisor_roles.py','codex_agent.py','cpu_kernel_validation.py')
save_json(folder/'controls.json', dict(host=initial,profile=profile,baseline=str(baseline),
    baseline_sha256=source_hash,target_gflops=1800,max_candidates=6,max_model_calls=108,
    max_seconds=1800,agent_timeout=180,prior_scores_imported=False,task=task,
    prior_phases=prior,implementation_commit=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),
    implementation_hashes={name:hashlib.sha256((repo/'sera'/name).read_bytes()).hexdigest() for name in modules},
    driver_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest()))
evaluator = HillsKernelEvaluator(workspace='/Users/vishnuv/Documents/Documents/kernel-opt')


def evaluate(source_dir, report_path, *, final, timeout):
    before = host_observation()
    check_power(before, initial)
    host_path = Path(report_path).with_suffix('.host.json')
    observations = dict(before=before)
    save_json(host_path, observations)
    try:
        report = evaluator(source_dir, report_path, final=final, timeout=timeout)
        print('SCORED', report_path, report.get('metrics'), flush=True)
        return report
    finally:
        after = host_observation()
        observations['after'] = after
        save_json(host_path, observations)
        check_power(after, initial)


def validate(source_path, output_path, *, timeout):
    if (reference/'LICENSE.libxsmm.md').read_text() not in Path(source_path).read_text():
        result = dict(passed=False,stage='license',error='LIBXSMM notice removed')
        save_json(output_path,result)
        return result
    return validate_cpu_kernel(source_path,output_path,timeout=timeout)


try:
    result = optimize_kernel(baseline=KernelCandidate('libxsmm-reference-with-unused-panel32',source,
        'Original full512 GEMM body plus an optional unused generated panel primitive'),
        propose=team,evaluate=evaluate,validate=validate,output_dir=folder/'search',
        max_candidates=6,target_gflops=1800,max_seconds=1800)
    print('RESULT',json.dumps({key:result.get(key) for key in
        ('status','target_met','final_gflops','winner_source','stop_reason')}),flush=True)
finally:
    if (folder/'search/result.json').exists():
        team.observe(json.loads((folder/'search/result.json').read_text())['trials'])
