"""Local Sera frontend and account server. Run: python3 web/server.py."""
import argparse
import hashlib
import hmac
import json
import os
import re
import secrets
import sqlite3
import sys
import threading
import time
from collections import defaultdict, deque
from http.cookies import SimpleCookie
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlsplit
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
# The proxy lives beside this file, which is not a package, so make it importable
# whether the server is started as `python3 web/server.py` or from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent))
try:
    import molab_proxy
except ImportError:
    # The marketing site and the local notebook must still come up without it;
    # the molab endpoints say so rather than the whole server refusing to start.
    molab_proxy = None
# The marimo WASM export. Generated by scripts/build_notebook.sh and ignored by
# git: it is ~27MB of vendored runtime assets that rebuild from source in one
# command, so it does not belong in history.
NOTEBOOK_DIR = ROOT / 'output' / 'notebook'
# Which molab notebook the GPU tab embeds. Override with SERA_MOLAB_URL once the
# synced notebook exists; molab mints a new id when you create one from GitHub.
DEFAULT_MOLAB_URL = 'https://molab.marimo.io/notebooks/nb_uP6EwkHWvZnXf4PnegaHhY/app'
MOLAB_URL = os.environ.get('SERA_MOLAB_URL', DEFAULT_MOLAB_URL)
NOTEBOOK_TYPES = ('.html', '.css', '.js', '.json', '.map', '.wasm', '.whl', '.zip',
                  '.woff', '.woff2', '.ttf', '.png', '.svg', '.ico', '.webmanifest', '.txt')
SESSION_SECONDS = 86400
# Shared walkthrough login, seeded on start so a fresh checkout can sign in immediately.
DEMO_EMAIL = 'demo@serademo.com'
DEMO_PASSWORD = 'clustersss'
# The molab relay listens on its own port because marimo bakes its base URL in at
# server start: a subpath proxy would serve a page whose assets point elsewhere.
DEFAULT_PROXY_PORT = 8878
# The lab polls status while a sandbox boots, and every probe is a round trip to
# molab's edge, so one answer stands in for the next few seconds.
MOLAB_STATUS_SECONDS = 5
# A sandbox that will not validate is left alone for a while rather than retried
# by every proxied asset on the page.
MOLAB_RETRY_SECONDS = 15
# One probe of a sandbox that is there answers fast; validating takes two round
# trips through molab's edge and happens while somebody is watching a spinner.
MOLAB_TIMEOUT = 4.0
MOLAB_CONNECT_TIMEOUT = 12.0


class Server(ThreadingHTTPServer):
    def __init__(self, port, database, demo_account=True, proxy_port=DEFAULT_PROXY_PORT):
        self.database = Path(database)
        self.database.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        self.database.touch(mode=0o600, exist_ok=True)
        os.chmod(self.database, 0o600)
        self.attempts = defaultdict(deque)
        self.lock = threading.Lock()
        self.proxy_port = proxy_port
        # Set only once the relay is actually listening, so the lab never gets
        # handed a proxy address that would refuse the connection.
        self.proxy_url = None
        self.molab_lock = threading.Lock()
        self.upstream = None
        self.molab_seen = None
        self.molab_retry = 0.0
        with self.connect() as db:
            db.executescript('''
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL,
                    salt TEXT NOT NULL, password_hash TEXT NOT NULL);
                CREATE TABLE IF NOT EXISTS sessions (
                    token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL,
                    expires REAL NOT NULL);
                CREATE TABLE IF NOT EXISTS molab (
                    id INTEGER PRIMARY KEY CHECK (id = 1), url TEXT NOT NULL,
                    token TEXT NOT NULL, connected REAL NOT NULL);
            ''')
        if demo_account:
            self.seed_demo_account()
        super().__init__(("127.0.0.1", port), Handler)

    def seed_demo_account(self):
        """Create the demo login once; a real account with that email is left alone."""
        with self.connect() as db:
            if db.execute('SELECT 1 FROM users WHERE email=?', (DEMO_EMAIL,)).fetchone():
                return
            salt = secrets.token_hex(16)
            db.execute('INSERT INTO users(email,salt,password_hash) VALUES(?,?,?)',
                       (DEMO_EMAIL, salt, password_hash(DEMO_PASSWORD, salt)))

    def connect(self):
        return sqlite3.connect(self.database)

    def user_for(self, cookie_header):
        """The signed-in account behind a Cookie header, or None.

        Split out of the handler because the proxy port answers a different
        request class entirely but must apply exactly this check.
        """
        with self.connect() as db:
            return db.execute('''SELECT users.id, users.email FROM sessions
                JOIN users ON users.id=sessions.user_id
                WHERE token_hash=? AND expires>?''',
                (token_hash(cookie_header), time.time())).fetchone()

    def molab_config(self):
        """The stored sandbox as (url, token), or None. The token stays here."""
        with self.connect() as db:
            return db.execute('SELECT url, token FROM molab WHERE id=1').fetchone()

    def molab_connect(self, upstream, token):
        """Remember a sandbox that has already validated."""
        with self.connect() as db:
            db.execute('INSERT OR REPLACE INTO molab VALUES(1,?,?,?)',
                       (upstream.url, token, time.time()))
        with self.molab_lock:
            self.upstream = upstream
            self.molab_seen = None
            self.molab_retry = 0.0

    def molab_disconnect(self):
        with self.connect() as db:
            db.execute('DELETE FROM molab')
        with self.molab_lock:
            self.upstream = None
            self.molab_seen = None
            self.molab_retry = 0.0

    def molab_upstream(self):
        """The live upstream for the proxy, or None.

        Called once per proxied request, so the common path is a lock and a
        field read. After a restart the stored sandbox is validated again,
        because molab mints a new session secret every time it boots.
        """
        if molab_proxy is None:
            return None
        with self.molab_lock:
            if self.upstream is not None:
                return self.upstream
            if time.time() < self.molab_retry:
                return None
            self.molab_retry = time.time() + MOLAB_RETRY_SECONDS
        row = self.molab_config()
        if not row:
            return None
        try:
            upstream = molab_proxy.validate(row[0], row[1], timeout=MOLAB_CONNECT_TIMEOUT)
        except Exception:
            # Deliberately silent: the access token was an argument, and an
            # unexpected traceback would carry it into the log.
            return None
        with self.molab_lock:
            self.upstream = upstream
        return upstream

    def molab_status(self):
        """What the lab shows about the sandbox. Cached, because the lab polls."""
        with self.molab_lock:
            if self.molab_seen and time.time() < self.molab_seen[0]:
                return self.molab_seen[1]
        row = self.molab_config()
        if not row:
            payload = {'connected': False, 'url': None, 'healthy': False,
                       'proxy_url': self.proxy_url, 'gpu': None,
                       'detail': 'No molab sandbox is connected yet.'}
        else:
            healthy, status, detail = molab_health(row[0])
            payload = {'connected': True, 'url': row[0], 'healthy': healthy,
                       'proxy_url': self.proxy_url, 'gpu': molab_gpu(status),
                       'detail': detail}
        with self.molab_lock:
            self.molab_seen = (time.time() + MOLAB_STATUS_SECONDS, payload)
            if not payload['healthy']:
                # A sandbox that stopped answering will have a new session secret
                # when it comes back, so the held credential is worthless.
                self.upstream = None
        return payload


def password_hash(password, salt):
    return hashlib.pbkdf2_hmac('sha256', password.encode(), bytes.fromhex(salt), 600000).hex()


def token_hash(cookie_header):
    """The stored form of the sera_session cookie, or '' when there is none."""
    cookie = SimpleCookie()
    try:
        cookie.load(cookie_header or '')
        token = cookie['sera_session'].value
    except (KeyError, ValueError):
        return ''
    return hashlib.sha256(token.encode()).hexdigest()


def molab_health(url, timeout=MOLAB_TIMEOUT):
    """One cheap GET that says whether the sandbox is still there.

    Returns (healthy, status payload, plain sentence for the lab). No token is
    sent: /api/status answers without one, which is why it is the probe.
    """
    request = Request(url.rstrip('/') + '/api/status', headers={'User-Agent': 'Sera'})
    try:
        with urlopen(request, timeout=timeout) as response:
            status = json.loads(response.read(65536).decode())
    except Exception:
        return False, {}, 'That sandbox is not answering. It may have been stopped.'
    if not isinstance(status, dict):
        return False, {}, 'That address answered, but not like a marimo notebook.'
    return True, status, 'Connected. The notebook is answering.'


def molab_gpu(status):
    """True only when the sandbox said so.

    Unknown stays None on purpose. Claiming a GPU nobody confirmed is the one
    thing this demo cannot afford to get wrong.
    """
    value = status.get('gpu')
    if isinstance(value, bool):
        return value
    if isinstance(value, str) and value.strip():
        return True
    return None


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT / 'output'), **kwargs)

    cacheable = False

    def end_headers(self):
        # X-Frame-Options governs who may embed these pages, not what they may
        # embed, and no Content-Security-Policy is sent, so nothing here blocks
        # the lab from framing the proxy port. Checked; left alone deliberately.
        self.send_header('Cache-Control',
                         'public, max-age=3600' if self.cacheable else 'no-store')
        self.send_header('X-Content-Type-Options', 'nosniff')
        self.send_header('X-Frame-Options', 'SAMEORIGIN')
        self.send_header('Referrer-Policy', 'same-origin')
        super().end_headers()

    def valid_host(self):
        return self.headers.get('Host') in {
            f'localhost:{self.server.server_port}', f'127.0.0.1:{self.server.server_port}'}

    def reply(self, status, data, cookie=None):
        body = json.dumps(data).encode()
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(body)))
        if cookie:
            self.send_header('Set-Cookie', cookie)
        self.end_headers()
        self.wfile.write(body)

    def redirect(self, path):
        self.send_response(303)
        self.send_header('Location', path)
        self.send_header('Content-Length', '0')
        self.end_headers()

    def token_hash(self):
        return token_hash(self.headers.get('Cookie', ''))

    def user(self):
        return self.server.user_for(self.headers.get('Cookie', ''))

    def serve_notebook(self, path, head):
        """Serve the exported marimo notebook, and nothing outside it.

        Unlike the rest of the site this is a directory tree rather than a flat
        allow-list, so containment is checked by resolving the target and
        confirming it is still inside NOTEBOOK_DIR. That survives '..', symlinks
        and percent-encoding, which a string prefix check would not.
        """
        if not self.user():
            self.redirect('/sign-in')
            return
        if not NOTEBOOK_DIR.is_dir():
            self.send_error(503, 'Notebook not built. Run scripts/build_notebook.sh')
            return
        relative = unquote(path[len('/notebook-app'):]).lstrip('/') or 'index.html'
        root = NOTEBOOK_DIR.resolve()
        target = (root / relative).resolve()
        if not target.is_relative_to(root) or not target.is_file():
            self.send_error(404)
            return
        if target.suffix not in NOTEBOOK_TYPES:
            self.send_error(404)
            return
        self.cacheable = target.name != 'index.html'
        self.directory = str(root)
        self.path = '/' + target.relative_to(root).as_posix()
        try:
            super().do_HEAD() if head else super().do_GET()
        finally:
            self.cacheable = False
            self.directory = str(ROOT / 'output')

    def molab(self, path, data):
        """Point the lab at a live molab sandbox.

        The access token is write-only: it goes into the database and is never
        returned to the browser, echoed in an error, or printed.
        """
        if not self.user():
            self.reply(401, {'error': 'Sign in to continue.'})
            return
        if path == '/api/molab/disconnect':
            self.server.molab_disconnect()
            self.reply(200, {'ok': True})
            return
        if molab_proxy is None:
            self.reply(503, {'error': 'Connecting a sandbox is not available in this build.'})
            return
        url, token = data.get('url', ''), data.get('token', '')
        if not isinstance(url, str) or not isinstance(token, str):
            self.reply(400, {'error': 'Enter the sandbox address and its access token.'})
            return
        url, token = url.strip(), token.strip()
        if not 0 < len(url) <= 512 or not 0 < len(token) <= 512:
            self.reply(400, {'error': 'Enter the sandbox address and its access token.'})
            return
        try:
            upstream = molab_proxy.validate(url, token, timeout=MOLAB_CONNECT_TIMEOUT)
        except molab_proxy.MolabError as error:
            self.reply(400, {'error': str(error)})
            return
        except Exception:
            # The token is in the arguments, so an unexpected traceback would
            # leak it into the log. Say the plain thing instead.
            self.reply(502, {'error': 'Could not reach that sandbox. '
                                      'Check the address and try again.'})
            return
        self.server.molab_connect(upstream, token)
        status = upstream.status if isinstance(upstream.status, dict) else {}
        self.reply(200, {'ok': True, 'url': upstream.url,
                         'proxy_url': self.server.proxy_url,
                         'status': {'version': status.get('version'),
                                    'mode': status.get('mode'),
                                    'filenames': status.get('filenames') or []}})

    def serve_get(self, head=False):
        if not self.valid_host():
            self.send_error(403)
            return
        path = urlsplit(self.path).path
        routes = {'/': 'index.html', '/sign-in': 'sign-in.html', '/get-started': 'get-started.html',
                  '/lab': 'sera-lab-preview.html', '/designs': 'sera-design-directions.html',
                  '/product': 'product.html', '/solutions': 'solutions.html',
                  '/models': 'models.html', '/resources': 'resources.html',
                  '/notebook': 'lab-notebook.html'}
        legacy = {'/' + filename: route for route, filename in routes.items()}
        routes.update({route: 'sera-lab-preview.html' for route in ('/lab/performance', '/lab/models', '/lab/trials')})
        legacy['/sera-design-preview.html'] = '/'
        if path in legacy:
            self.redirect(legacy[path])
            return
        if path != '/' and path.endswith('/') and path.rstrip('/') in routes:
            self.redirect(path.rstrip('/'))
            return
        if path == '/api/metrics' and not head:
            if not self.user():
                self.reply(401, {'error': 'Sign in to continue.'})
                return
            ledger = ROOT / 'runs' / 'ledger.jsonl'
            try:
                rows = [json.loads(line) for line in ledger.read_text().splitlines() if line.strip()] if ledger.exists() else []
                self.reply(200, {'trials': rows, 'source': 'runs/ledger.jsonl',
                                 'updated': ledger.stat().st_mtime if ledger.exists() else None})
            except (OSError, ValueError):
                self.reply(503, {'error': 'The run ledger is being updated. Try refreshing shortly.'})
            return
        if path == '/api/config' and not head:
            if not self.user():
                self.reply(401, {'error': 'Sign in to continue.'})
                return
            self.reply(200, {'molab_url': MOLAB_URL, 'proxy_url': self.server.proxy_url})
            return
        if path == '/api/molab/status' and not head:
            if not self.user():
                self.reply(401, {'error': 'Sign in to continue.'})
                return
            self.reply(200, self.server.molab_status())
            return
        if path == '/api/session' and not head:
            user = self.user()
            self.reply(200 if user else 401, {'email': user[1]} if user else {'error': 'Sign in to continue.'})
            return
        if path == '/notebook-app' or path.startswith('/notebook-app/'):
            self.serve_notebook(path, head)
            return
        if (path in ('/lab', '/designs', '/notebook') or path.startswith('/lab/')) and not self.user():
            self.redirect('/sign-in')
            return
        if path in ('/sign-in', '/get-started') and self.user():
            self.redirect('/notebook')
            return
        # Serve only public frontend files, never account databases or directory listings.
        name = routes.get(path, path.removeprefix('/'))
        allowed = {p.name for p in (ROOT / 'output').iterdir()
                   if p.is_file() and p.suffix in ('.html', '.css', '.js', '.svg', '.png', '.ico')}
        if name not in allowed:
            self.send_error(404)
            return
        self.path = '/' + name
        if head:
            super().do_HEAD()
        else:
            super().do_GET()

    def do_GET(self):
        self.serve_get()

    def do_HEAD(self):
        self.serve_get(head=True)

    def do_POST(self):
        if not self.valid_host() or self.headers.get('Origin') != 'http://' + self.headers.get('Host', ''):
            self.reply(403, {'error': 'Please submit this form from the Sera website.'})
            return
        path = urlsplit(self.path).path
        if path not in ('/api/sign-in', '/api/sign-up', '/api/sign-out',
                        '/api/molab/connect', '/api/molab/disconnect'):
            self.reply(404, {'error': 'Page not found.'})
            return
        if self.headers.get('Content-Type', '').split(';')[0] != 'application/json':
            self.reply(415, {'error': 'Expected a JSON request.'})
            return
        try:
            length = int(self.headers.get('Content-Length', '0'))
            if not 0 < length <= 8192:
                raise ValueError()
            data = json.loads(self.rfile.read(length))
            if not isinstance(data, dict):
                raise ValueError()
        except (ValueError, UnicodeDecodeError):
            self.reply(400, {'error': 'Invalid request.'})
            return
        if path == '/api/sign-out':
            with self.server.connect() as db:
                db.execute('DELETE FROM sessions WHERE token_hash=?', (self.token_hash(),))
            self.reply(200, {'ok': True}, 'sera_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0')
            return
        if path.startswith('/api/molab/'):
            self.molab(path, data)
            return
        with self.server.lock:
            attempts = self.server.attempts[self.client_address[0]]
            now = time.time()
            while attempts and attempts[0] < now - 60:
                attempts.popleft()
            if len(attempts) >= 15:
                self.reply(429, {'error': 'Too many attempts. Please wait a minute and try again.'})
                return
            attempts.append(now)
        email, password = data.get('email', ''), data.get('password', '')
        if not isinstance(email, str) or not isinstance(password, str):
            self.reply(400, {'error': 'Enter your email and password.'})
            return
        email = email.strip().lower()
        if len(email) > 254 or not re.fullmatch(r'[^\s@]+@[^\s@]+\.[^\s@]+', email) or not 10 <= len(password) <= 128:
            self.reply(400, {'error': 'Use a valid email and a password of 10–128 characters.'})
            return
        with self.server.connect() as db:
            if path == '/api/sign-up':
                salt = secrets.token_hex(16)
                try:
                    cursor = db.execute('INSERT INTO users(email,salt,password_hash) VALUES(?,?,?)',
                                        (email, salt, password_hash(password, salt)))
                    user_id = cursor.lastrowid
                except sqlite3.IntegrityError:
                    self.reply(409, {'error': 'An account with this email already exists. Sign in instead.'})
                    return
            else:
                row = db.execute('SELECT id,salt,password_hash FROM users WHERE email=?', (email,)).fetchone()
                actual = password_hash(password, row[1] if row else '00' * 16)
                if not row or not hmac.compare_digest(actual, row[2]):
                    self.reply(401, {'error': 'Email or password is incorrect.'})
                    return
                user_id = row[0]
            db.execute('DELETE FROM sessions WHERE expires<=? OR token_hash=?', (time.time(), self.token_hash()))
            token = secrets.token_urlsafe(32)
            db.execute('INSERT INTO sessions VALUES(?,?,?)',
                       (hashlib.sha256(token.encode()).hexdigest(), user_id, time.time() + SESSION_SECONDS))
        self.reply(200, {'ok': True, 'redirect': '/notebook'},
                   f'sera_session={token}; HttpOnly; SameSite=Strict; Path=/; Max-Age={SESSION_SECONDS}')


def start_proxy(server):
    """Relay the molab session from our own origin, in the background.

    The sandbox tells the browser only a short list of sites may frame it, and
    we are not on it, so relaying is the only way to show the notebook in the
    lab. A failure here costs the GPU tab, not the site, so it never raises.
    """
    if molab_proxy is None:
        print('molab proxy off: web/molab_proxy.py is missing.', flush=True)
        return None
    try:
        proxy = molab_proxy.ProxyServer(
            server.proxy_port, server.molab_upstream,
            lambda handler: server.user_for(handler.headers.get('Cookie', '')) is not None)
    except OSError as error:
        print(f'molab proxy off: port {server.proxy_port} is unavailable ({error}).', flush=True)
        return None
    server.proxy_url = f'http://localhost:{proxy.server_port}'
    threading.Thread(target=proxy.serve_forever, daemon=True).start()
    return proxy


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', type=int, default=8877)
    parser.add_argument('--proxy-port', type=int, default=DEFAULT_PROXY_PORT,
                        help='loopback port that relays the molab notebook')
    parser.add_argument('--database', default=str(ROOT / '.local' / 'accounts.sqlite3'))
    parser.add_argument('--no-demo-account', action='store_true',
                        help='skip seeding the shared demo login')
    args = parser.parse_args()
    server = Server(args.port, args.database, demo_account=not args.no_demo_account,
                    proxy_port=args.proxy_port)
    proxy = start_proxy(server)
    print(f'Sera is running at http://localhost:{server.server_port}', flush=True)
    if proxy:
        print(f'molab proxy is running at {server.proxy_url}', flush=True)
    if not args.no_demo_account:
        print(f'Demo login: {DEMO_EMAIL} / {DEMO_PASSWORD}', flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.server_close()
        if proxy:
            proxy.server_close()
